### ISSUE TITLE
run time error : tokenize is not defined by exports

### ISSUE THREAD

**Issue by SOunit** [SOunit/book_link#73]
# error
build is successful, still when client run, client gives error below.
this comes from node v17 error. so let's use node v16.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: 
Package subpath './lib/tokenize' is not defined by "exports" 
in /tmp/workspace/node_modules/postcss-safe-parser/node_modules/postcss/package.json
```

# refs
- how to avoid error
https://github.com/facebook/create-react-app/issues/11565

**Comment by SOunit** [comment]
error fix.

**Comment by Pratikkadam00** [comment]
Can you please tell me how did you fix the error

**Comment by SOunit** [comment]
@Pratikkadam00 

hi. sorry I do not remember well, but from the comment, I guess I just changed the version of node from v17 to v16.

- how to check node version
```
node -v
```

- how to check available node version if you use nodenv
```
nodenv versions
```
